"""empty message

Revision ID: 508e47b6d90d
Revises: 
Create Date: 2022-03-17 14:03:30.025666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508e47b6d90d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Properties',
    sa.Column('propertyid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=75), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('no_of_bedrooms', sa.Integer(), nullable=True),
    sa.Column('no_of_bathrooms', sa.String(length=10), nullable=True),
    sa.Column('types', sa.String(length=25), nullable=True),
    sa.Column('price', sa.String(length=35), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('image_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('propertyid'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Properties')
    # ### end Alembic commands ###
