"""empty message

Revision ID: c079ab0f570b
Revises: 08bd396ecf22
Create Date: 2022-03-19 15:16:47.033617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c079ab0f570b'
down_revision = '08bd396ecf22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Properties', sa.Column('option', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Properties', 'option')
    # ### end Alembic commands ###
